listen:
  port: 4040
  address: "0.0.0.0"

#consul:
#  enable: true
#  address: "localhost:8500"
#  datacenter: dc1
#  scheme: http
#  token: ""
#  service:
#    id: "nginx-exporter"
#    name: "nginx-exporter"
#    tags: ["foo", "bar"]

namespaces:
  - name: nginx
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" rt=$request_time uct=\"$upstream_connect_time\" uht=\"$upstream_header_time\" urt=\"$upstream_response_time\" us=\"$upstream_status\""
    source_files:
      - "/var/log/nginx/nginx_exporter.log"
  #- name: app2
  #- format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time"
  #- source_files:
  #-   - /var/log/nginx/app2/access.log
